### PR TITLE
Made plenty of improvements, fixed Workflows and Haxe 4.3

### PR DESCRIPTION
**Pull request by moxie-coder**
Including a compile fix for Haxe 4.3, upgrading the workflows too to 4.3 since Neko is breaking them, and removing validscore since it's useless, new Difficulty code & a crash fix from 0.7.3 and other general improvements (including some cleanup)

I might work on the new stage system from 0.7 to clean playstate soon, but for now this will do

### CODE REVIEW

**Comment by uwenalil** [comment]
what the hell
I might merge this later, I'm just taking a break rn.

**Comment by moxie-coder** [comment]
> what the hell I might merge this later, I'm just taking a break rn.

sure thing

**Comment by VideoBotYT** [comment]
> Including a compile fix for Haxe 4.3, upgrading the workflows too to 4.3 since Neko is breaking them, and removing validscore since it's useless, new Difficulty code & a crash fix from 0.7.3 and other general improvements (including some cleanup)
> 
> I might work on the new stage system from 0.7 to clean playstate soon, but for now this will do

idk why you did a fix for Haxe 4.3 so idk yet if i'm gonna merge this yet and idk what libs i need to update

**Comment by CharGoldenYT** [comment]
QUICK NOTE: This will break compilation on any version below 4.3 if it contains any of [these](https://haxe.org/manual/expression-null-coalesce.html) PLEASE make sure to convert anything that looks similar to `value ?? "fallback"
` to looking like `value != null ? value : "fallback"`so as to maintain compatibility with Haxe versions starting with Haxe 4.2

**Comment by moxie-coder** [comment]
> This commit does not contain any of what was in a previous edit of this message, however, an update to the libraries devs are using are required to compile it seems
> 
> Note
> 
> I am not an official dev.

well, specifically lock libraries to specific versions because some people just can’t use right versions

**Comment by moxie-coder** [comment]
> This PR causes the pause menu to once again be broken. (On Haxe 4.2.5)
> 
> Anytime you try to change difficulties it gives an error image

yup, because newer flixel breaks it, and I know a fix for it, just haven’t gotten to it yet

**Comment by CharGoldenYT** [comment]
> > This PR causes the pause menu to once again be broken. (On Haxe 4.2.5)
> > Anytime you try to change difficulties it gives an error image
> 
> yup, because newer flixel breaks it, and I know a fix for it, just haven’t gotten to it yet

And you made a PR despite not sorting out the fact that it broke something?

**Comment by moxie-coder** [comment]
> > > This PR causes the pause menu to once again be broken. (On Haxe 4.2.5)
> > > Anytime you try to change difficulties it gives an error image
> > 
> > 
> > yup, because newer flixel breaks it, and I know a fix for it, just haven’t gotten to it yet
> 
> And you made a PR despite not sorting out the fact that it broke something?

I was fixing it for myself because I wasn’t even able to compile it, it was a fucking mess for Christ sake and I tried to make it better

**Comment by CharGoldenYT** [comment]
That's understandable, and I wasn't trying to be rude, but if you knew about the issue before the PR, why would you open it before fixing it?

**Comment by moxie-coder** [comment]
> That's understandable, and I wasn't trying to be rude, but if you knew about the issue before the PR, why would you open it before fixing it?

I opened this PR *after* fixing it, I tested it before I fixed them, I didn’t know about that issue because I didn’t get that issue, but I will fix it soon

**Comment by CharGoldenYT** [comment]
Ah. got it.

**Comment by moxie-coder** [comment]
and also side tangent, it was to fix the chart editor crashing *properly* since it wasn’t fixed properly, and it still isn’t entirely fixed, just doesn’t crash now, but I’m gonna figure it out later, I work my ass day and night, I’m usually busy with stuff irl, or other things online, so I’m usually either up late or sleeping during the day, but point is, I didn’t have the patience or energy to fix everything yet

**Comment by CharGoldenYT** [comment]
Ah, Only other crash fixes done was for the fact that having no vocals crashed it due to missing files.
(At least what I've contributed, and are aware of.)

**Comment by moxie-coder** [comment]
> Ah, Only other crash fixes done was for the fact that having no vocals crashed it due to missing files. (At least what I've contributed, and are aware of.)

the main problem in the chart editor is it’s trying to load from the assets folder, not from the mods folder, it’s not accounting for charts in there, and I don’t know whether to blame that on the shit code that videobot did, or because this uses 0.6.3, btu either way, I’m gonna figure it out, I didn’t test everything because it was 3/4 in the morning, I was and am still tired, and I didn’t account for everything because there’s a lot

**Comment by VideoBotYT** [comment]
> > Ah, Only other crash fixes done was for the fact that having no vocals crashed it due to missing files. (At least what I've contributed, and are aware of.)
> 
> the main problem in the chart editor is it’s trying to load from the assets folder, not from the mods folder whenever you try to load a chart in the mods folder, it’s not accounting for charts in there, and I don’t know whether to blame that on the shit Ctrl C + Ctrl V code that videobot did, or because this uses 0.6.3, btu either way, I’m gonna figure it out, I didn’t test everything because it was 3/4 in the morning, I was and am still tired, and I didn’t account for everything because there’s a lot

i think it crashes bc you didn't select the correct mods folder. in the editor menu use UI_LEFT or UI_RIGHT keys to select a different modpack you can see what modpack you selected at the bottom middle of your screen if you're in the editors menu

**Comment by moxie-coder** [comment]
> > > Ah, Only other crash fixes done was for the fact that having no vocals crashed it due to missing files. (At least what I've contributed, and are aware of.)
> > 
> > 
> > the main problem in the chart editor is it’s trying to load from the assets folder, not from the mods folder whenever you try to load a chart in the mods folder, it’s not accounting for charts in there, and I don’t know whether to blame that on the shit Ctrl C + Ctrl V code that videobot did, or because this uses 0.6.3, btu either way, I’m gonna figure it out, I didn’t test everything because it was 3/4 in the morning, I was and am still tired, and I didn’t account for everything because there’s a lot
> 
> i think it crashes bc you didn't select the correct mods folder. in the editor menu use UI_LEFT or UI_RIGHT keys to select a different modpack you can see what modpack you selected at the bottom middle of your screen if you're in the editors menu

usually for me anyways, it usually detects the charts without problem, even if I didn’t do any of that, but if that’s what fixes it fine then, but if it’s a problem despite not being in a mod pack, then it’s definitely a big issue

**Comment by CharGoldenYT** [comment]
> > > > Ah, Only other crash fixes done was for the fact that having no vocals crashed it due to missing files. (At least what I've contributed, and are aware of.)
> 
> > > 
> 
> > > 
> 
> > > the main problem in the chart editor is it’s trying to load from the assets folder, not from the mods folder whenever you try to load a chart in the mods folder, it’s not accounting for charts in there, and I don’t know whether to blame that on the shit Ctrl C + Ctrl V code that videobot did, or because this uses 0.6.3, btu either way, I’m gonna figure it out, I didn’t test everything because it was 3/4 in the morning, I was and am still tired, and I didn’t account for everything because there’s a lot
> 
> > 
> 
> > i think it crashes bc you didn't select the correct mods folder. in the editor menu use UI_LEFT or UI_RIGHT keys to select a different modpack you can see what modpack you selected at the bottom middle of your screen if you're in the editors menu
> 
> 
> 
> usually for me anyways, it usually detects the charts without problem, even if I didn’t do any of that, but if that’s what fixes it fine then, but if it’s a problem despite not being in a mod pack, then it’s definitely a big issue

That is, infact, how psych works, I have charts in the main mods/data directory and it loads fine for me

**Comment by VideoBotYT** [comment]
sorry but i wont merge it

**Comment by moxie-coder** [comment]
> sorry but i wont merge it

Okay then

**Comment by AnAmmar** [comment]
I will add

**Pull request closed without merging**
