### PR TITLE
PR/Feature Request: Add window changing lua functions

### PR DESCRIPTION
**Pull request by CharGoldenYT**
changeWindowTitle
changeWindowIcon

This is a hybrid pr and feature request lmao
not neccassary, and quite simple really, but would be cool to have.

### CODE REVIEW

**Comment by CharGoldenYT** [comment]
hold on wait i forgor to sync my repo like a dummy

**Comment by uwenalil** [comment]
this very **epic**

**Comment by uwenalil** [comment]
i just realized theres already an event for this

**Comment by CharGoldenYT** [comment]
😔

**Pull request merged**
