### PR TITLE
Credit Rozebud!

### PR DESCRIPTION
**Pull request by soushimiya**
Lil Buddies is not from JS Engine, it's from FPS Plus.
I've seen a lot of people crediting things incorrectly.
(btw icon made by me)

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
true

**Comment by VideoBotYT** [comment]
> Lil Buddies is not from JS Engine, it's from FPS Plus.
> I've seen a lot of people crediting things incorrectly.
> (btw icon made by me)

i'm verry sorry i didn't know that. i only saw them in JS. i will add the credit in but JS will still be credited in bc there's still code from JS in Universe Engine

**Comment by moxie-coder** [comment]
> > Lil Buddies is not from JS Engine, it's from FPS Plus.
> > I've seen a lot of people crediting things incorrectly.
> > (btw icon made by me)
> 
> i'm verry sorry i didn't know that. i only saw them in JS. i will add the credit in but JS will still be credited in bc there's still code from JS in Universe Engine

yeah, and I'm one of the devs

**Comment by VideoBotYT** [comment]
it's gonna be in the credits when 0.4.4 is out

**Pull request closed without merging**
